export type CategoryLink = { id?: number; title: string; description?: string; query: string };
export type ReportCard = { id?: number; title: string; description?: string; icon?: string; backTitle?: string; backDescription?: string; buttonLabel?: string; href: string };
export type Footer = { disclaimer?: string; navLinks?: NavLink[] };
export type NavLink = { id?: number; label: string; href: string; children?: NavLink[] };
export type HomepageData = { title: string; hero: { eyebrow?: string; title: string; subtitle?: string; searchPlaceholder?: string; searchButtonLabel?: string; categories?: CategoryLink[]; builtByText?: string }; insightsSection: { title: string; description?: string; cards?: ReportCard[] }; footer?: Footer };
export type PageData = { title: string; slug: string; subtitle?: string; pageType?: 'standard'|'report'; heroStyle?: 'simple-blue'|'none'; body?: string; tableData?: { columns: string[]; rows: string[][] }; embedUrl?: string; footer?: Footer };

export const defaultFooter: Footer = { disclaimer: 'Yukon Connect Hub is an independent platform and is not affiliated with the Government of Yukon. While we aim to provide accurate and up-to-date information sourced from official public records, we do not accept responsibility for any errors, omissions, or outcomes resulting from its use.', navLinks: [{label:'Home',href:'/'},{label:'Reports',href:'/reports',children:[{label:'Fiscal Year Trend',href:'/fiscal-year-trend'},{label:'Tender Types',href:'/tender-acquisition-method'}]},{label:'Contact',href:'/contact'}] };
export const fallbackHomepage: HomepageData = { title: 'Yukon Connect', hero: { eyebrow: 'Unlock new opportunities with tailored resources, tools, and insights to help your business grow and thrive in Yukon and Northern Canada.', title: 'Empowering Northern Entrepreneurs', searchPlaceholder: 'Type here...', searchButtonLabel: 'Search', builtByText: 'Proudly built by Bizont', categories: [{title:'Services',description:'IT Maintenance, Professional Services, Design, and more...',query:'services'},{title:'Goods',description:'Cleaning, Office Supplies and more...',query:'goods'},{title:'Construction',description:'Construction Goods, and more...',query:'construction'}] }, insightsSection: { title: 'Stay Updated with the Latest Business Insights', description: 'Explore the most recent reports and opportunities for your business in Yukon.', cards: [{title:'Fiscal Year Trend',description:'This report analyzes the fiscal year trends for contract awards from FY 2021 to 2025, highlighting seasonal patterns and the balance between new contracts and extensions.',icon:'calendar',backTitle:'Optimizing Procurement Strategies',backDescription:'Understanding these trends can help businesses optimize their procurement strategies and maximize contracting opportunities.',buttonLabel:'Read More',href:'/fiscal-year-trend'},{title:'Tender Acquisition Method',description:'This report examines the most used tender acquisition methods from FY 2021 to 2025, highlighting key trends in contract allocation and spending.',icon:'file-contract',backTitle:'Understanding Contract Allocation Trends',backDescription:'Analyzing acquisition methods helps businesses navigate procurement opportunities and maximize contract potential.',buttonLabel:'Read More',href:'/tender-acquisition-method'}] }, footer: defaultFooter };
export const fallbackFiscalYear: PageData = { title: 'Fiscal Year Trend 2021–2025', slug: 'fiscal-year-trend', subtitle: 'Understanding Contract Trends Over Time', pageType: 'report', heroStyle: 'simple-blue', body: '## Understanding Contract Trends Over Time\n\nContract activity across fiscal years shows recurring procurement cycles and a consistent balance between original contracts and extensions.\n\nThe data highlights how spending and volume shift year over year, helping businesses plan around seasonal opportunities and recurring government needs.\n\n**Tip:** Review both total contract amount and extension percentage to understand where long-term vendor relationships may shape future opportunities.\n\nThe table below summarizes contract volume, value, and award mix by fiscal year.', tableData: { columns: ['Fiscal Year','Total # contracts','Total contract amount','Original contracts','Extensions'], rows: [['2021–2022','16664','$754,100,208','81.54%','18.46%'],['2022–2023','15539','$702,701,254','80.94%','19.06%'],['2023–2024','16704','$856,973,732','81.99%','18.01%'],['2024–2025','15451','$626,211,673','82.39%','17.61%']] }, footer: defaultFooter };
export async function getHomepage(): Promise<HomepageData> { return fetchStrapi('/api/homepage?populate[hero][populate]=*&populate[insightsSection][populate]=*&populate[footer][populate]=*', fallbackHomepage); }
export async function getPageBySlug(slug: string): Promise<PageData | null> { const fb = slug==='fiscal-year-trend' ? fallbackFiscalYear : null; return fetchStrapi(`/api/pages?filters[slug][$eq]=${encodeURIComponent(slug)}&populate=*`, fb, true); }
async function fetchStrapi<T>(path: string, fallback: T, list = false): Promise<T> { const base = process.env.STRAPI_URL ?? process.env.NEXT_PUBLIC_STRAPI_URL; if (!base) return fallback; try { const res = await fetch(`${base.replace(/\/$/,'')}${path}`, { next: { revalidate: 60 } }); if (!res.ok) throw new Error(`Strapi returned ${res.status}`); const json = await res.json(); const data = list ? json.data?.[0] : json.data; return (data?.attributes ?? data ?? fallback) as T; } catch (e) { if (process.env.NODE_ENV === 'development') console.warn('Using local fallback content because Strapi is unavailable:', e); return fallback; } }
